### PR TITLE
Fix bug in reademe

### PR DESCRIPTION
**Pull request by qq976739120**
hey,You might forget to import something

### CODE REVIEW

**Comment by serderovsh** [comment]
It would be more correct
```python
from tronapi import Tron, HttpProvider
```

**Comment by serderovsh** [comment]
HttpProvider - not even required

```python
from tronapi import Tron

full_node = 'https://api.trongrid.io'
solidity_node = 'https://api.trongrid.io'
event_server = 'https://api.trongrid.io'

tron = Tron(full_node=full_node,
            solidity_node=solidity_node,
            event_server=event_server)
```

**Comment by qq976739120** [comment]
@serderovsh I push my code now,merge it

**Comment by serderovsh** [comment]
Thanks!

**Pull request merged**
